/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PbChip {
        "clickable": boolean;
        "disabled": boolean;
    }
    interface PbChips {
    }
    interface PlanbColorPicker {
        "customColorCode": string;
        "customColorName": string;
        "dark": boolean;
        "disabled": boolean;
        "size": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPbChipElement extends Components.PbChip, HTMLStencilElement {
    }
    var HTMLPbChipElement: {
        prototype: HTMLPbChipElement;
        new (): HTMLPbChipElement;
    };
    interface HTMLPbChipsElement extends Components.PbChips, HTMLStencilElement {
    }
    var HTMLPbChipsElement: {
        prototype: HTMLPbChipsElement;
        new (): HTMLPbChipsElement;
    };
    interface HTMLPlanbColorPickerElement extends Components.PlanbColorPicker, HTMLStencilElement {
    }
    var HTMLPlanbColorPickerElement: {
        prototype: HTMLPlanbColorPickerElement;
        new (): HTMLPlanbColorPickerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pb-chip": HTMLPbChipElement;
        "pb-chips": HTMLPbChipsElement;
        "planb-color-picker": HTMLPlanbColorPickerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PbChip {
        "clickable"?: boolean;
        "disabled"?: boolean;
    }
    interface PbChips {
    }
    interface PlanbColorPicker {
        "customColorCode"?: string;
        "customColorName"?: string;
        "dark"?: boolean;
        "disabled"?: boolean;
        "onColorSelected"?: (event: CustomEvent<{code: string, name: string}>) => void;
        "size"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pb-chip": PbChip;
        "pb-chips": PbChips;
        "planb-color-picker": PlanbColorPicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pb-chip": LocalJSX.PbChip & JSXBase.HTMLAttributes<HTMLPbChipElement>;
            "pb-chips": LocalJSX.PbChips & JSXBase.HTMLAttributes<HTMLPbChipsElement>;
            "planb-color-picker": LocalJSX.PlanbColorPicker & JSXBase.HTMLAttributes<HTMLPlanbColorPickerElement>;
        }
    }
}
